# Generated by Django 5.2.5 on 2025-08-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=100, verbose_name='Nome do Responsável')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('nome_aluno', models.CharField(max_length=100, verbose_name='Nome do Aluno')),
                ('nivel_ensino', models.CharField(choices=[('infantil', 'Educação Infantil'), ('fundamental 1', 'Fundamental 1'), ('fundamental 2', 'Fundamental 2'), ('medio', 'Ensino Médio')], max_length=20, verbose_name='Nível de Ensino')),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], max_length=10, verbose_name='Turno')),
                ('data_visita', models.DateField(verbose_name='Data da Visita')),
                ('horario_visita', models.TimeField(verbose_name='Horário da Visita')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Agendamento de Visita',
                'verbose_name_plural': 'Agendamentos de Visita',
                'ordering': ['-created_at'],
            },
        ),
    ]
