# Generated by Django 5.2.6 on 2025-09-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxi', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='fbclid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='gclid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='utm_content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='utm_term',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
