# Generated by Django 5.2.6 on 2025-09-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxi', '0004_contato_fbclid_contato_gclid_contato_utm_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='consentimento_analytics',
            field=models.BooleanField(default=False),
        ),
    ]
