# Generated by Django 5.2.6 on 2025-09-16 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxi', '0005_contato_consentimento_analytics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.DeleteModel(
            name='TrackingEvents',
        ),
        migrations.DeleteModel(
            name='TrackSession',
        ),
    ]
